# Generated by Django 5.2.9 on 2025-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_volume',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
