# Generated by Django 5.2.9 on 2025-12-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_url',
        ),
    ]
